資料視覺化套件 
 靜態:seaborn
 動態:
 plotly
 bokeh

In [1]:
1+1

2

In [2]:
a=1

In [3]:
a

1

In [4]:
a+1

2

# 基本資料型態

In [5]:
a = 3
type(a)

int

In [6]:
b = 'Hello World!'
type(b)

str

In [7]:
c = 1.1
type(c)

float

In [8]:
d = [a, b, c]
type(d)

list

In [9]:
d

[3, 'Hello World!', 1.1]

In [10]:
e = (a, b, c)
type(e)

tuple

In [11]:
f ={
    'key_1': d,
    'key_2': e
}
type(f)

dict

In [12]:
f

{'key_1': [3, 'Hello World!', 1.1], 'key_2': (3, 'Hello World!', 1.1)}

### 如何從上述資料型態找出指定位置的值?

In [13]:
d[0]

3

### 如何更改上述資料型態指定位置的值?

In [14]:
e[0]='Hello World'

TypeError: 'tuple' object does not support item assignment

### 小練習: 請產生一個list，包含字串'Hello World'，整數'2'，以及tuple(1,2,3)

In [1]:
a=['Hello World', 2, (1, 2, 3)]
a

['Hello World', 2, (1, 2, 3)]

## list 應用

In [15]:
a=[ 'Hello World' , 2 , (1, 2, 3) ]

In [16]:
a.append(4)
a

['Hello World', 2, (1, 2, 3), 4]

In [17]:
a.pop()

4

In [18]:
a

['Hello World', 2, (1, 2, 3)]

# 基本運算

In [19]:
1+1

2

In [20]:
3-1

2

In [21]:
2*3

6

In [22]:
7/2

3.5

In [23]:
2**3

8

In [24]:
7//2

3

In [25]:
7%2

1

In [26]:
a=1
a+=2
print(a)

3


### 小練習: 請用python計算出$ \frac{1+4}{2}\times 20 \div (1+3)$

In [27]:
( 1 + 4 ) / 2 * 20 / ( 1 + 3)

12.5

# 函式 function

In [28]:
def sayhelloworld():
    print('Hello World!')

In [29]:
sayhelloworld()

Hello World!


In [30]:
def say_hello_world():
    ''' say hello world
    '''
    print('Hello World!')

In [31]:
say_hello_world()

Hello World!


In [32]:
sayhelloworld?

In [33]:
say_hello_world?

In [34]:
def sayhello(text):
    print( 'Hello '+ text + '!')

In [35]:
sayhello('World')

Hello World!


# 邏輯判斷

In [36]:
2 > 3

False

In [37]:
1+2 == 3

True

In [38]:
1+1 !=3

True

In [39]:
a = 2 > 3

In [40]:
type(a)

bool

In [41]:
2 > 1 and 2 > 3

False

In [42]:
2 > 1 or 2 > 3

True

# 流程控制

### While 迴圈

In [43]:
a=0

while a<5:
    print(a)
    a = a+1


0
1
2
3
4


### for 迴圈

In [44]:
range(10)

range(0, 10)

In [45]:
type( range(10) )

range

In [46]:
list( range(10) )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


### 小練習:利用function以及迴圈概念，print(10)次hello world

In [48]:
def sayhello(word):
    print( 'Hello '+ word + '!')

for i in range(10):
    sayhello('World')
    

Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!


### 巢狀迴圈

In [49]:
for i in range( 3 ):
    print( '外圈: {}'.format(i) )
    for j in range( 3 ):
        print( '   內圈: {}'.format(j) )

外圈: 0
   內圈: 0
   內圈: 1
   內圈: 2
外圈: 1
   內圈: 0
   內圈: 1
   內圈: 2
外圈: 2
   內圈: 0
   內圈: 1
   內圈: 2


### 小練習:利用巢狀迴圈，製作99乘法表

In [50]:
for i in range(1,10):
    for j in range(1,10):
        print( i * j )

1
2
3
4
5
6
7
8
9
2
4
6
8
10
12
14
16
18
3
6
9
12
15
18
21
24
27
4
8
12
16
20
24
28
32
36
5
10
15
20
25
30
35
40
45
6
12
18
24
30
36
42
48
54
7
14
21
28
35
42
49
56
63
8
16
24
32
40
48
56
64
72
9
18
27
36
45
54
63
72
81


In [1]:
for i in range(1,10):
    for j in range(1,10):
        print( "{} * {} = {}".format(i, j, i*j))

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81


# numpy進行主要運算

### 99乘法表

In [51]:
#引用套件
import numpy as np

In [52]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(1, 10).reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [54]:
# 把資料列先變成 9 X 1 與 1 X 9的矩陣，再相乘，最後會變 9 X 9
result = np.multiply(
    # 定義出資料列，再reshape成9 X 1
    np.arange(1, 10).reshape(9, 1),
    # 定義出資料列，再reshape成1 X 9
    np.arange(1, 10).reshape(1, 9)
)
# multiply就是把矩陣相乘
result

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [55]:
type(result)

numpy.ndarray

### 比較for loop和純np的速度

In [56]:
import time

In [57]:
# for loop
start_time = time.time()

n = 1000
result = []
for i in range(1, n):
    for j in range(1, n):
        output = i * j
        result.append(output)
result = np.array(result).reshape(n-1, n-1)

end_time = time.time()
print('{} seconds taken'.format(round(end_time - start_time, 4)))

0.2758 seconds taken


In [58]:
# 純np
start_time = time.time()

n = 1000
result = np.multiply(
    np.arange(1, n).reshape(n-1, 1),
    np.arange(1, n).reshape(1, n-1)
)

end_time = time.time()
print('{} seconds taken'.format(round(end_time - start_time, 4)))

0.004 seconds taken


# 進階練習

In [1]:
#定義物件名稱
class Account():
    #初始化數據，self之後的參數，是創立物件時，所需要輸入的部分
    def __init__(self, name, balance):
        self.name = name
        self.balance = balance
        
    def deposit(self, amount):  #存款動作: amount代表存入金額
        if amount <= 0:
            print('must be positive')
        else:
            self.balance += amount
        
    def withdraw(self, amount): #取款動作: amount代表取款金額
        if amount <= self.balance:
            self.balance -= amount
        else:
            print('balance not enough')
        
    def check(self):   #查看目前餘額 format後的參數，可以填在前面的{}中
        print('{}目前存款剩餘: {}'.format(self.name, self.balance))
    
    def transfer(self, amount, OtherAccount):  #轉帳功能，將兩個帳戶物件互動
        if amount <= self.balance:
            self.balance -= amount
            OtherAccount.balance += amount
        else:
            print('balance not enough')

In [2]:
ac1 = Account('小明', 100000)
ac2 = Account('小美', 50000)

In [3]:
ac1.check()
ac2.check()

小明目前存款剩餘: 100000
小美目前存款剩餘: 50000


In [4]:
ac1.withdraw(10000)
ac1.check()

小明目前存款剩餘: 90000


In [5]:
ac1.deposit(100)
ac1.check()

小明目前存款剩餘: 90100


In [6]:
ac1.transfer(10000, ac2)
ac1.check()
ac2.check()

小明目前存款剩餘: 80100
小美目前存款剩餘: 60000
